export const GENSYNC_START = Symbol.for("gensync:v1:start");
export const GENSYNC_SUSPEND = Symbol.for("gensync:v1:suspend");

export const GENSYNC_EXPECTED_START = "GENSYNC_EXPECTED_START";
export const GENSYNC_EXPECTED_SUSPEND = "GENSYNC_EXPECTED_SUSPEND";
export const GENSYNC_OPTIONS_ERROR = "GENSYNC_OPTIONS_ERROR";
export const GENSYNC_RACE_NONEMPTY = "GENSYNC_RACE_NONEMPTY";
export const GENSYNC_ERRBACK_NO_CALLBACK = "GENSYNC_ERRBACK_NO_CALLBACK";
